spring.application.name=BarberShop
server.port=80


#Para mosrtrar cosas en el log
spring.jpa.properties.hibernate.format_sql=true
loggin.level.org.hibernate.SQL=DEBUG
loggin.level.org.type.descriptor.SQL.BasicBinder=TRACE
